### ISSUE TITLE
Test plan for the 0.3 series

### ISSUE THREAD

**Issue by arteymix** [valum-framework/valum#163]
The coverage is around 53%, which is quite terrible. It is important to introduce tests that cover as many documented usage of the framework as possible.

- [x] ensure that properties are well forwarded in filtered requests and responses
- [x] full coverage for the rule new features (group, wildcard, optional, ...)
- [x] cover `OPTIONS` and return value from #166 
- [x] rule generation (when available in #158)
- [x] check how `null` entries are handled in a context
- [x] cover servers with `listen` and `uris`
- [x] cover multiple `listen` calls #132 
- [x] test pkg-config files

As always, missing regions can be identified from the [coverage results](https://coveralls.io/github/valum-framework/valum).

**Comment by arteymix** [comment]
The new `Server.listen` call and `Server.uris` property can be used to test VSGI implementations.

It would be neat to use subprocess support in GLib test framework to make actual assertion on served endpoints.

**Comment by arteymix** [comment]
The coverage is broken since abe14348cd7d7cad257801718a45c8a8699c6b73...

**Comment by arteymix** [comment]
The coverage is fine and the new features have already been tested. There's some work to do in `VSGI.Application` however, but that can wait.
